/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Button } from '@mui/material';
import { styled } from '@mui/material/styles';
import { HeaderProps } from 'types';
import useHeader from 'components/Header/useHeader';

const ScreenDesktop: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100vw',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: data.currentVariant === 'ScreenMobile' ? `30px 20px` : `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
  margin: '0 auto',
  maxWidth: '1440px',
}));

const Hero: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
  overflow: `hidden`,
});

const FillHero: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: data.currentVariant === 'ScreenMobile' ? `column` : `row`,
  justifyContent: `flex-start`,
  alignItems: data.currentVariant === 'ScreenMobile' ? `center` : `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
}));

const LeftSide: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `180px 0px 180px 60px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flex: `1`,
  margin:
    data.currentVariant === 'ScreenTablet'
      ? `0px 0px 0px 10px`
      : data.currentVariant === 'ScreenMobile'
      ? `10px 0px 0px 0px`
      : `0px`,
}));

const Text: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const EmpoweringTheModernWSpan1: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(51, 51, 51, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `66px`,
  letterSpacing: `-3.96px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  textAlign: 'unset',
  fontSynthesis: 'unset',
  alignSelf: 'unset',
  margin: 'unset',
});

const EmpoweringTheModernWSpan2: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(242, 80, 34, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `66px`,
  letterSpacing: `-3.96px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  textAlign: 'unset',
  fontSynthesis: 'unset',
  alignSelf: 'unset',
  margin: 'unset',
});

const EmpoweringTheModernW: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `66px`,
  letterSpacing: `-3.96px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const TransformYourOrganiz: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 0.75)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `133.39999914169312%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
}));

const Btns: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `40px 0px 0px 0px`,
});

const BtnsPosition: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  flex: `1`,
  margin: `0px`,
});

const ButtonContained: any = styled(Button, {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ theme, data }: any) => ({
  margin: `0px`,
  color: theme.palette['Primary']['Contrast'],
  fontStyle: theme.typography['Components']['Button Font - Large'].fontStyle,
  fontFamily: theme.typography['Components']['Button Font - Large'].fontFamily,
  fontWeight: theme.typography['Components']['Button Font - Large'].fontWeight,
  fontSize: theme.typography['Components']['Button Font - Large'].fontSize,
  letterSpacing:
    theme.typography['Components']['Button Font - Large'].letterSpacing,
  lineHeight: theme.typography['Components']['Button Font - Large'].lineHeight,
  textDecoration:
    theme.typography['Components']['Button Font - Large'].textDecoration,
  textTransform:
    theme.typography['Components']['Button Font - Large'].textTransform,
}));

const ButtonOutlined: any = styled(Button, {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ theme, data }: any) => ({
  margin: `0px 0px 0px 22px`,
  color: theme.palette['Primary']['Main'],
  fontStyle: theme.typography['Components']['Button Font - Large'].fontStyle,
  fontFamily: theme.typography['Components']['Button Font - Large'].fontFamily,
  fontWeight: theme.typography['Components']['Button Font - Large'].fontWeight,
  fontSize: theme.typography['Components']['Button Font - Large'].fontSize,
  letterSpacing:
    theme.typography['Components']['Button Font - Large'].letterSpacing,
  lineHeight: theme.typography['Components']['Button Font - Large'].lineHeight,
  textDecoration:
    theme.typography['Components']['Button Font - Large'].textDecoration,
  textTransform:
    theme.typography['Components']['Button Font - Large'].textTransform,
}));

const Video: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `60px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flex: `1`,
  margin:
    data.currentVariant === 'ScreenTablet'
      ? `0px 0px 0px 10px`
      : data.currentVariant === 'ScreenMobile'
      ? `10px 0px 0px 0px`
      : `0px`,
}));

const Pic1: any = styled('img')({
  height: `476px`,
  width: `564px`,
  objectFit: `cover`,
  margin: `0px`,
});

const Pic: any = styled('div')({
  backgroundImage: `url(assets/images/Header_Pic.png)`,
  backgroundPosition: `center`,
  backgroundSize: `contain`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const Pic2: any = styled('div')({
  backgroundImage: `url(assets/images/Header_Pic_2.png)`,
  backgroundPosition: `center`,
  backgroundSize: `100%`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const Pic3: any = styled('div')({
  backgroundImage: `url(assets/images/Header_Pic_3.png)`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const Pic4: any = styled('div')({
  backgroundImage: `url(assets/images/Header_Pic_4.png)`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const LeftSide1: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `45px 0px 60px 30px`,
  boxSizing: `border-box`,
  flex: `1`,
  margin: data.currentVariant === 'ScreenMobile' ? `10px 0px 0px 0px` : `0px`,
  width: data.currentVariant === 'ScreenMobile' ? `379px` : 'unset',
}));

const Text1: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const EmpoweringTheModernW1Span1: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(51, 51, 51, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `52px`,
  letterSpacing: `-3.12px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  textAlign: 'unset',
  fontSynthesis: 'unset',
  alignSelf: 'unset',
  margin: 'unset',
});

const EmpoweringTheModernW1Span2: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(242, 80, 34, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `52px`,
  letterSpacing: `-3.12px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  textAlign: 'unset',
  fontSynthesis: 'unset',
  alignSelf: 'unset',
  margin: 'unset',
});

const EmpoweringTheModernW1: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `52px`,
  letterSpacing: `-3.12px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const TransformYourOrganiz1: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 0.75)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `133.39999914169312%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
}));

const Btns1: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 90px 0px 0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `40px 0px 0px 0px`,
});

const BtnsPosition1: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const ButtonContained1: any = styled(Button, {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ theme, data }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
  color: theme.palette['Primary']['Contrast'],
  fontStyle: theme.typography['Components']['Button Font - Large'].fontStyle,
  fontFamily: theme.typography['Components']['Button Font - Large'].fontFamily,
  fontWeight: theme.typography['Components']['Button Font - Large'].fontWeight,
  fontSize: theme.typography['Components']['Button Font - Large'].fontSize,
  letterSpacing:
    theme.typography['Components']['Button Font - Large'].letterSpacing,
  lineHeight: theme.typography['Components']['Button Font - Large'].lineHeight,
  textDecoration:
    theme.typography['Components']['Button Font - Large'].textDecoration,
  textTransform:
    theme.typography['Components']['Button Font - Large'].textTransform,
}));

const ButtonOutlined1: any = styled(Button, {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ theme, data }: any) => ({
  alignSelf: `stretch`,
  margin: `22px 0px 0px 0px`,
  color: theme.palette['Primary']['Main'],
  fontStyle: theme.typography['Components']['Button Font - Large'].fontStyle,
  fontFamily: theme.typography['Components']['Button Font - Large'].fontFamily,
  fontWeight: theme.typography['Components']['Button Font - Large'].fontWeight,
  fontSize: theme.typography['Components']['Button Font - Large'].fontSize,
  letterSpacing:
    theme.typography['Components']['Button Font - Large'].letterSpacing,
  lineHeight: theme.typography['Components']['Button Font - Large'].lineHeight,
  textDecoration:
    theme.typography['Components']['Button Font - Large'].textDecoration,
  textTransform:
    theme.typography['Components']['Button Font - Large'].textTransform,
}));

const Video1: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `60px 0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flex: `1`,
  margin:
    data.currentVariant === 'ScreenTablet'
      ? `0px 0px 0px 10px`
      : data.currentVariant === 'ScreenMobile'
      ? `10px 0px 0px 0px`
      : `0px`,
}));

const Pic11: any = styled('img')({
  height: `323px`,
  width: `379px`,
  objectFit: `cover`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Pic5: any = styled('div')({
  backgroundImage: `url(assets/images/Header_Pic_5.png)`,
  backgroundPosition: `center`,
  backgroundSize: `contain`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const Pic6: any = styled('div')({
  backgroundImage: `url(assets/images/Header_Pic_6.png)`,
  backgroundPosition: `center`,
  backgroundSize: `100%`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const Pic7: any = styled('div')({
  backgroundImage: `url(assets/images/Header_Pic_7.png)`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const Pic8: any = styled('div')({
  backgroundImage: `url(assets/images/Header_Pic_8.png)`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const Video2: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: data.currentVariant === 'ScreenMobile' ? 'unset' : `335px`,
  margin: data.currentVariant === 'ScreenTablet' ? `0px 0px 0px 10px` : `0px`,
  height: data.currentVariant === 'ScreenMobile' ? `230px` : 'unset',
}));

const Pic12: any = styled('img', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  height:
    data.currentVariant === 'ScreenTablet'
      ? `38px`
      : data.currentVariant === 'ScreenMobile'
      ? `38px`
      : `230px`,
  width: `276px`,
  objectFit: `cover`,
  flex: `1`,
  margin: `0px`,
}));

const Pic9: any = styled('div')({
  backgroundImage: `url(assets/images/Header_Pic_9.png)`,
  backgroundPosition: `center`,
  backgroundSize: `contain`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const Pic10: any = styled('div')({
  backgroundImage: `url(assets/images/Header_Pic_10.png)`,
  backgroundPosition: `center`,
  backgroundSize: `100%`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const Pic13: any = styled('div')({
  backgroundImage: `url(assets/images/Header_Pic_11.png)`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const Pic14: any = styled('div')({
  backgroundImage: `url(assets/images/Header_Pic_12.png)`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const LeftSide2: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  width: data.currentVariant === 'ScreenMobile' ? 'unset' : `335px`,
  margin:
    data.currentVariant === 'ScreenTablet'
      ? `0px 0px 0px 10px`
      : data.currentVariant === 'ScreenMobile'
      ? `10px 0px 0px 0px`
      : `0px`,
}));

const Text2: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const EmpoweringTheModernW2Span1: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(51, 51, 51, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `46px`,
  letterSpacing: `-2.76px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  textAlign: 'unset',
  fontSynthesis: 'unset',
  alignSelf: 'unset',
  margin: 'unset',
});

const EmpoweringTheModernW2Span2: any = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(242, 80, 34, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `46px`,
  letterSpacing: `-2.76px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  textAlign: 'unset',
  fontSynthesis: 'unset',
  alignSelf: 'unset',
  margin: 'unset',
});

const EmpoweringTheModernW2: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `46px`,
  letterSpacing: `-2.76px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const TransformYourOrganiz2: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 0.75)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `133.39999914169312%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `20px 0px 0px 0px`,
}));

const Btns2: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `40px 0px 0px 0px`,
});

const BtnsPosition2: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const ButtonContained2: any = styled(Button, {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ theme, data }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
  color: theme.palette['Primary']['Contrast'],
  fontStyle: theme.typography['Components']['Button Font - Large'].fontStyle,
  fontFamily: theme.typography['Components']['Button Font - Large'].fontFamily,
  fontWeight: theme.typography['Components']['Button Font - Large'].fontWeight,
  fontSize: theme.typography['Components']['Button Font - Large'].fontSize,
  letterSpacing:
    theme.typography['Components']['Button Font - Large'].letterSpacing,
  lineHeight: theme.typography['Components']['Button Font - Large'].lineHeight,
  textDecoration:
    theme.typography['Components']['Button Font - Large'].textDecoration,
  textTransform:
    theme.typography['Components']['Button Font - Large'].textTransform,
}));

const ButtonOutlined2: any = styled(Button, {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ theme, data }: any) => ({
  alignSelf: `stretch`,
  margin: `22px 0px 0px 0px`,
  color: theme.palette['Primary']['Main'],
  fontStyle: theme.typography['Components']['Button Font - Large'].fontStyle,
  fontFamily: theme.typography['Components']['Button Font - Large'].fontFamily,
  fontWeight: theme.typography['Components']['Button Font - Large'].fontWeight,
  fontSize: theme.typography['Components']['Button Font - Large'].fontSize,
  letterSpacing:
    theme.typography['Components']['Button Font - Large'].letterSpacing,
  lineHeight: theme.typography['Components']['Button Font - Large'].lineHeight,
  textDecoration:
    theme.typography['Components']['Button Font - Large'].textDecoration,
  textTransform:
    theme.typography['Components']['Button Font - Large'].textTransform,
}));

function Header(props: HeaderProps): JSX.Element {
  const { data } = useHeader();

  return (
    <ScreenDesktop className={props.className} data={data}>
      <Hero>
        <FillHero data={data}>
          {!(data.currentVariant === 'ScreenTablet') &&
            !(data.currentVariant === 'ScreenMobile') && (
              <LeftSide data={data}>
                <Text>
                  <EmpoweringTheModernW>
                    <EmpoweringTheModernWSpan1>{`EMPOWERING THE `}</EmpoweringTheModernWSpan1>
                    <EmpoweringTheModernWSpan2>{`MODERN WORKPLACE`}</EmpoweringTheModernWSpan2>
                  </EmpoweringTheModernW>
                  <TransformYourOrganiz>
                    {`Transform your organization with Surface for Business, Microsoft 365, customized services and training by MOWO.`}
                  </TransformYourOrganiz>
                </Text>
                <Btns>
                  <BtnsPosition>
                    <ButtonContained
                      variant="contained"
                      size={'large'}
                      color={'primary'}
                      disabled={false}
                      data={data}
                    >
                      {'Book a meeting'}
                    </ButtonContained>
                    <ButtonOutlined
                      variant="outlined"
                      size={'large'}
                      color={'primary'}
                      disabled={false}
                      data={data}
                    >
                      {'See devices'}
                    </ButtonOutlined>
                  </BtnsPosition>
                </Btns>
              </LeftSide>
            )}
          {!(data.currentVariant === 'ScreenTablet') &&
            !(data.currentVariant === 'ScreenMobile') && (
              <Video data={data}>
                <Pic1
                  src={`assets/images/Header_Pic.png`}
                  loading="lazy"
                  alt={'Pic 1'}
                />
                {false && <Pic></Pic>}
                {false && <Pic2></Pic2>}
                {false && <Pic3></Pic3>}
                {false && <Pic4></Pic4>}
              </Video>
            )}
          {data.currentVariant === 'ScreenTablet' && (
            <LeftSide1 data={data}>
              <Text1>
                <EmpoweringTheModernW1>
                  <EmpoweringTheModernW1Span1>{`EMPOWERING THE `}</EmpoweringTheModernW1Span1>
                  <EmpoweringTheModernW1Span2>{`MODERN WORKPLACE`}</EmpoweringTheModernW1Span2>
                </EmpoweringTheModernW1>
                <TransformYourOrganiz1>
                  {`Transform your organization with Surface for Business, Microsoft 365, customized services and training by MOWO.`}
                </TransformYourOrganiz1>
              </Text1>
              <Btns1>
                <BtnsPosition1>
                  <ButtonContained1
                    variant="contained"
                    size={'large'}
                    color={'primary'}
                    disabled={false}
                    data={data}
                  >
                    {'Book a meeting'}
                  </ButtonContained1>
                  <ButtonOutlined1
                    variant="outlined"
                    size={'large'}
                    color={'primary'}
                    disabled={false}
                    data={data}
                  >
                    {'See devices'}
                  </ButtonOutlined1>
                </BtnsPosition1>
              </Btns1>
            </LeftSide1>
          )}
          {data.currentVariant === 'ScreenTablet' && (
            <Video1 data={data}>
              <Pic11
                src={`assets/images/Header_Pic_1_1.png`}
                loading="lazy"
                alt={'Pic 1'}
              />
              {false && <Pic5></Pic5>}
              {false && <Pic6></Pic6>}
              {false && <Pic7></Pic7>}
              {false && <Pic8></Pic8>}
            </Video1>
          )}
          {data.currentVariant === 'ScreenMobile' && (
            <Video2 data={data}>
              <Pic12
                data={data}
                src={`assets/images/Header_Pic_1_2.png`}
                loading="lazy"
                alt={'Pic 1'}
              />
              {false && <Pic9></Pic9>}
              {false && <Pic10></Pic10>}
              {false && <Pic13></Pic13>}
              {false && <Pic14></Pic14>}
            </Video2>
          )}
          {data.currentVariant === 'ScreenMobile' && (
            <LeftSide2 data={data}>
              <Text2>
                <EmpoweringTheModernW2>
                  <EmpoweringTheModernW2Span1>{`EMPOWERING THE `}</EmpoweringTheModernW2Span1>
                  <EmpoweringTheModernW2Span2>{`MODERN WORKPLACE`}</EmpoweringTheModernW2Span2>
                </EmpoweringTheModernW2>
                <TransformYourOrganiz2>
                  {`Transform your organization with Surface for Business, Microsoft 365, customized services and training by MOWO.`}
                </TransformYourOrganiz2>
              </Text2>
              <Btns2>
                <BtnsPosition2>
                  <ButtonContained2
                    variant="contained"
                    size={'large'}
                    color={'primary'}
                    disabled={false}
                    data={data}
                  >
                    {'Book a meeting'}
                  </ButtonContained2>
                  <ButtonOutlined2
                    variant="outlined"
                    size={'large'}
                    color={'primary'}
                    disabled={false}
                    data={data}
                  >
                    {'See devices'}
                  </ButtonOutlined2>
                </BtnsPosition2>
              </Btns2>
            </LeftSide2>
          )}
        </FillHero>
      </Hero>
    </ScreenDesktop>
  );
}

export default Header;
