/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import useHeaderResponsiveSize from './useHeaderResponsiveSize';

/* These are the possible values for the current variant. Use this to change the currentVariant dynamically.
Please don't modify */
const variantOptions = {
  Property1Desktop: 'Property1Desktop',
  Property1Tablet: 'Property1Tablet',
  Property1Mobile: 'Property1Mobile',
};

const useHeader = () => {
  const [currentVariant, setCurrentVariant] = React.useState<string>(
    variantOptions['Property1Desktop']
  );

  const breakpointsVariant = useHeaderResponsiveSize();

  React.useEffect(() => {
    if (breakpointsVariant !== currentVariant) {
      setCurrentVariant(breakpointsVariant);
    }
  }, [breakpointsVariant]);

  const data: any = { currentVariant };

  const fns: any = { setCurrentVariant };

  return { data, fns };
};

export default useHeader;
