/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import ProductBox from 'components/ProductBox/ProductBox';
import { ProductListProps } from 'types';
import useProductList from 'components/ProductList/useProductList';
import useProductBox from 'components/ProductBox/useProductBox';
import { ProductBoxProps } from 'types';

const ProductList1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: 'auto',
});

const ProductBox1: any = styled(ProductBox)<ProductBoxProps>(({ theme }: any) => ({
  width: `311px`,
  zIndex: `0`,
  margin: `0px`,
}));

function ProductBox(props: ProductBoxProps): JSX.Element {
  const { data } = useProductBox();

  return (

      <ProductBox1 id={data.product[0].id} isProduct={data.products[0].isProduct}/>

  );
}

export default ProductList;
