/**********************************************************************
 *
 *   Types file generated by Quest
 *
 *   Types for the components props go in this file
 *   To set up custom types for the components props, edit the corresponding types in this file
 *   Once you edit a type to no longer by "any", be careful to not override it on your next export
 *   Verify diff before merging
 *
 *   For help and further details refer to:
 *   https://docs.quest.ai/react/fundamentals/exporting-code
 *
 *
 **********************************************************************/














export interface ProductBox6Props {
  className?: any;
};



export interface ProductBox5Props {
  className?: any;
};




export interface ProductBox4Props {
  className?: any;
};





export interface ProductBox3Props {
  className?: any;
};






export interface ProductBox2Props {
  className?: any;
};







export interface ProductBox1Props {
  className?: any;
};








export interface CustomerCardProps {
  className?: any;
}














export interface ModernWorkplaceProps {
  className?: any;
}














export interface NavbarProps {
  className?: any;
}














export interface HeaderProps {
  className?: any;
}














export interface SidebarProps {
  className?: any;
}














export interface Link1Props {
  className?: any;
}














export interface CustomerCasesProps {
  className?: any;
}














export interface FooterProps {
  className?: any;
}














export interface ProductSectionSurfaceHubDeviceProps {
  className?: any;
}














export interface ProductCardProps {
  className?: any;
}














export interface MowoFunProps {
  className?: any;
}
