/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
const useProductCard = () => {
  const data: any = {
    productTitle: [
      'Product Title',
    ],
    productDesc: [
      'Product Description',
    ],
  };
  const getImageSrc = (): any => {
    return './assets/images/Product-Image-1.png'
  };
  const handleButtonClick = (): any => {};

  const fns: any = { getImageSrc, handleButtonClick };

  return { data, fns };
};

export default useProductCard;
