/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { SectionHeaderProps } from 'types';
import useSectionHeader from 'components/SectionHeader/useSectionHeader';

const ScreenDesktopColorPr: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `24px 0px`,
  boxSizing: `border-box`,
  height: 'auto',
});

const Titlecontainer: any = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Title1: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 1)`,
  fontStyle: theme.typography['Typography']['H2'].fontStyle,
  fontFamily: theme.typography['Typography']['H2'].fontFamily,
  fontWeight: theme.typography['Typography']['H2'].fontWeight,
  fontSize: theme.typography['Typography']['H2'].fontSize,
  letterSpacing: theme.typography['Typography']['H2'].letterSpacing,
  lineHeight: theme.typography['Typography']['H2'].lineHeight,
  textDecoration: theme.typography['Typography']['H2'].textDecoration,
  textTransform: theme.typography['Typography']['H2'].textTransform,
  margin: `0px`,
}));

const Title2: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: theme.palette['Secondary']['Main'],
  fontStyle: theme.typography['Typography']['H2'].fontStyle,
  fontFamily: theme.typography['Typography']['H2'].fontFamily,
  fontWeight: theme.typography['Typography']['H2'].fontWeight,
  fontSize: theme.typography['Typography']['H2'].fontSize,
  letterSpacing: theme.typography['Typography']['H2'].letterSpacing,
  lineHeight: theme.typography['Typography']['H2'].lineHeight,
  textDecoration: theme.typography['Typography']['H2'].textDecoration,
  textTransform: theme.typography['Typography']['H2'].textTransform,
  margin: `0px 0px 0px 16px`,
}));

const LoremIpsumDolorSitAm: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 0.75)`,
  fontStyle: theme.typography['Typography']['H5'].fontStyle,
  fontFamily: theme.typography['Typography']['H5'].fontFamily,
  fontWeight: theme.typography['Typography']['H5'].fontWeight,
  fontSize: theme.typography['Typography']['H5'].fontSize,
  letterSpacing: theme.typography['Typography']['H5'].letterSpacing,
  lineHeight: theme.typography['Typography']['H5'].lineHeight,
  textDecoration: theme.typography['Typography']['H5'].textDecoration,
  textTransform: theme.typography['Typography']['H5'].textTransform,
  alignSelf: `stretch`,
  margin: `16px 0px 0px 0px`,
}));

function SectionHeader(props: SectionHeaderProps): JSX.Element {
  const { data } = useSectionHeader();

  return (
    <ScreenDesktopColorPr className={props.className}>
      <Titlecontainer>
        <Title1>{data.headerContent.title1}</Title1>
        <Title2>{data.headerContent.title2}</Title2>
      </Titlecontainer>
      <LoremIpsumDolorSitAm>{data.headerContent.tagline}</LoremIpsumDolorSitAm>
    </ScreenDesktopColorPr>
  );
}

export default SectionHeader;
