/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft';
import { SvgIcon } from '@mui/material';
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
import { styled } from '@mui/material/styles';
import CustomerCard from 'components/CustomerCard/CustomerCard';
import { CustomerCasesProps } from 'types';
import useCustomerCases from 'components/CustomerCases/useCustomerCases';

const ScreenDesktop: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
});

const Rows: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ theme, data }: any) => ({
  backgroundColor: `rgba(248, 248, 248, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding:
    data.currentVariant === 'ScreenTablet'
      ? `60px 45px 120px 45px`
      : data.currentVariant === 'ScreenMobile'
      ? `30px`
      : `90px 60px 150px 60px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: '0 auto',
  overflow: `hidden`,
  maxWidth:
    data.currentVariant === 'ScreenTablet'
      ? `unset`
      : data.currentVariant === 'ScreenMobile'
      ? `unset`
      : `1440px`,
}));

const EmpoweringSuccessStoSpan1: any = styled('span', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(51, 51, 51, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `56px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  textAlign: 'unset',
  fontSynthesis: 'unset',
  alignSelf: 'unset',
  margin: 'unset',
}));

const EmpoweringSuccessStoSpan2: any = styled('span', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(127, 186, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `56px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  textAlign: 'unset',
  fontSynthesis: 'unset',
  alignSelf: 'unset',
  margin: 'unset',
}));

const EmpoweringSuccessSto: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `56px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin:
    data.currentVariant === 'ScreenTablet'
      ? `30px 0px 0px 0px`
      : data.currentVariant === 'ScreenMobile'
      ? `15px 0px 0px 0px`
      : `0px`,
}));

const RevolutionizingTheWo: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ theme, data }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 0.75)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `27px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `133.39999914169312%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin:
    data.currentVariant === 'ScreenMobile'
      ? `15px 0px 0px 0px`
      : `30px 0px 0px 0px`,
}));

const Customers: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin:
    data.currentVariant === 'ScreenMobile'
      ? `15px 0px 0px 0px`
      : `30px 0px 0px 0px`,
  overflow: `hidden`,
}));

const CustomerCard1: any = styled(CustomerCard)(({ theme }: any) => ({
  margin: `0px`,
}));

const CustomerCard2: any = styled(CustomerCard)(({ theme }: any) => ({
  margin: `0px 0px 0px 90px`,
}));

const CaseBackground: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  backgroundImage: `url(assets/images/CustomerCases_case_background.png)`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `15px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `210px 0px 0px 0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `450px`,
  margin:
    data.currentVariant === 'ScreenMobile'
      ? `15px 0px 0px 0px`
      : `30px 0px 0px 0px`,
}));

const CaseContent: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(241, 241, 241, 0.95)`,
  borderRadius: `15px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `45px`,
  boxSizing: `border-box`,
  width: `660px`,
  margin: `0px`,
  overflow: `hidden`,
}));

const CaseText: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const ReykjavikUniversity: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `133.39999914169312%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`,
}));

const WithMicrosoftSurface: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 0.75)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `150%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `12px 0px 0px 0px`,
}));

const DownloadPdf: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(127, 186, 0, 1)`,
  boxShadow: `0px 3px 1px rgba(0, 0, 0, 0.2), 0px 2px 2px rgba(0, 0, 0, 0.14), 0px 1px 5px rgba(0, 0, 0, 0.12)`,
  borderRadius: `4px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `8px 22px`,
  boxSizing: `border-box`,
  margin: `30px 0px 0px 0px`,
  overflow: `hidden`,
}));

const Base: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const MaskedIcon: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `18px`,
  height: `22px`,
  margin: `0px`,
});

const Vector: any = styled('img')({
  height: `16.56px`,
  width: `14px`,
  position: `absolute`,
  left: `2px`,
  top: `3px`,
});

const Button1: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `15px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `26px`,
  textTransform: `uppercase`,
  margin: `0px 0px 0px 8px`,
}));

const MaskedIcon1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `18px`,
  height: `22px`,
  margin: `0px 0px 0px 8px`,
});

const EmpoweringSuccessSto1Span1: any = styled('span', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(51, 51, 51, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `48px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  textAlign: 'unset',
  fontSynthesis: 'unset',
  alignSelf: 'unset',
  margin: 'unset',
}));

const EmpoweringSuccessSto1Span2: any = styled('span', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(127, 186, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `48px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  textAlign: 'unset',
  fontSynthesis: 'unset',
  alignSelf: 'unset',
  margin: 'unset',
}));

const EmpoweringSuccessSto1: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `48px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin:
    data.currentVariant === 'ScreenTablet'
      ? `0px`
      : data.currentVariant === 'ScreenMobile'
      ? `15px 0px 0px 0px`
      : `30px 0px 0px 0px`,
}));

const RevolutionizingTheWo1: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ theme, data }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 0.75)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `23px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `133.39999914169312%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin:
    data.currentVariant === 'ScreenMobile'
      ? `15px 0px 0px 0px`
      : `30px 0px 0px 0px`,
}));

const Customers1: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin:
    data.currentVariant === 'ScreenMobile'
      ? `15px 0px 0px 0px`
      : `30px 0px 0px 0px`,
  overflow: `hidden`,
}));

const CustomerCard3: any = styled(CustomerCard)(({ theme }: any) => ({
  margin: `0px`,
}));

const CustomerCard4: any = styled(CustomerCard)(({ theme }: any) => ({
  margin: `0px 0px 0px 60px`,
}));

const CustomerCard5: any = styled(CustomerCard)(({ theme }: any) => ({
  margin: `0px 0px 0px 60px`,
}));

const CaseBackground1: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  backgroundImage: `url(assets/images/CustomerCases_case_background_1.png)`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `15px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `210px 0px 0px 0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `420px`,
  margin:
    data.currentVariant === 'ScreenMobile'
      ? `15px 0px 0px 0px`
      : `30px 0px 0px 0px`,
}));

const CaseContent1: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(241, 241, 241, 0.95)`,
  borderRadius: `15px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `30px`,
  boxSizing: `border-box`,
  width: `600px`,
  margin: `0px`,
  overflow: `hidden`,
}));

const CaseText1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const ReykjavikUniversity1: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `26px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `133.39999914169312%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`,
}));

const WithMicrosoftSurface1: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 0.75)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `150%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `12px 0px 0px 0px`,
}));

const DownloadPdf1: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(127, 186, 0, 1)`,
  boxShadow: `0px 3px 1px rgba(0, 0, 0, 0.2), 0px 2px 2px rgba(0, 0, 0, 0.14), 0px 1px 5px rgba(0, 0, 0, 0.12)`,
  borderRadius: `4px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `8px 22px`,
  boxSizing: `border-box`,
  margin: `30px 0px 0px 0px`,
  overflow: `hidden`,
}));

const Base1: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const MaskedIcon2: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `18px`,
  height: `22px`,
  margin: `0px`,
});

const Vector1: any = styled('img')({
  height: `16.56px`,
  width: `14px`,
  position: `absolute`,
  left: `2px`,
  top: `3px`,
});

const Button2: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `14px`,
  letterSpacing: `0.4000000059604645px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `uppercase`,
  margin: `0px 0px 0px 8px`,
}));

const MaskedIcon3: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `18px`,
  height: `22px`,
  margin: `0px 0px 0px 8px`,
});

const EmpoweringSuccessSto2Span1: any = styled('span', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(51, 51, 51, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `39px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  textAlign: 'unset',
  fontSynthesis: 'unset',
  alignSelf: 'unset',
  margin: 'unset',
}));

const EmpoweringSuccessSto2Span2: any = styled('span', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  whiteSpace: `pre-wrap`,
  color: `rgba(127, 186, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `39px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  textAlign: 'unset',
  fontSynthesis: 'unset',
  alignSelf: 'unset',
  margin: 'unset',
}));

const EmpoweringSuccessSto2: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `39px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `100%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: data.currentVariant === 'ScreenMobile' ? `0px` : `30px 0px 0px 0px`,
}));

const RevolutionizingTheWo2: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ theme, data }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 0.75)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `133.39999914169312%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin:
    data.currentVariant === 'ScreenMobile'
      ? `15px 0px 0px 0px`
      : `30px 0px 0px 0px`,
}));

const Customers2: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `10px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin:
    data.currentVariant === 'ScreenMobile'
      ? `15px 0px 0px 0px`
      : `30px 0px 0px 0px`,
  overflow: `hidden`,
}));

const CustomerCard6: any = styled(CustomerCard)(({ theme }: any) => ({
  margin: `0px`,
}));

const CustomerCard7: any = styled(CustomerCard)(({ theme }: any) => ({
  margin: `0px 0px 0px 30px`,
}));

const CustomerCard8: any = styled(CustomerCard)(({ theme }: any) => ({
  margin: `0px 0px 0px 30px`,
}));

const Cases: any = styled('div', {
  shouldForwardProp: (prop: any) => !['data'].includes(prop.toString()),
})(({ data }: any) => ({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin:
    data.currentVariant === 'ScreenMobile'
      ? `15px 0px 0px 0px`
      : `30px 0px 0px 0px`,
}));

const CaseBackground2: any = styled('div')({
  backgroundImage: `url(assets/images/CustomerCases_case_background_2.png)`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `15px 15px 0px 0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  alignSelf: `stretch`,
  height: `300px`,
  margin: `0px`,
});

const CaseContent2: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(241, 241, 241, 0.95)`,
  borderRadius: `0px 0px 15px 15px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `30px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
  overflow: `hidden`,
}));

const CaseText2: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const ReykjavikUniversity2: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `22px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `133.39999914169312%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`,
}));

const WithMicrosoftSurface2: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 0.75)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `150%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `12px 0px 0px 0px`,
}));

const DownloadPdf2: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(127, 186, 0, 1)`,
  boxShadow: `0px 3px 1px rgba(0, 0, 0, 0.2), 0px 2px 2px rgba(0, 0, 0, 0.14), 0px 1px 5px rgba(0, 0, 0, 0.12)`,
  borderRadius: `4px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `8px 22px`,
  boxSizing: `border-box`,
  margin: `15px 0px 0px 0px`,
  overflow: `hidden`,
}));

const Base2: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const MaskedIcon4: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `18px`,
  height: `22px`,
  margin: `0px`,
});

const Vector2: any = styled('img')({
  height: `16.56px`,
  width: `14px`,
  position: `absolute`,
  left: `2px`,
  top: `3px`,
});

const Button3: any = styled('div')(({ theme }: any) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Roboto`,
  fontWeight: `500`,
  fontSize: `13px`,
  letterSpacing: `0.46000000834465027px`,
  textDecoration: `none`,
  lineHeight: `22px`,
  textTransform: `uppercase`,
  margin: `0px 0px 0px 8px`,
}));

const MaskedIcon5: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `18px`,
  height: `22px`,
  margin: `0px 0px 0px 8px`,
});

function CustomerCases(props: CustomerCasesProps): JSX.Element {
  const { data } = useCustomerCases();

  return (
    <ScreenDesktop className={props.className}>
      <Rows data={data}>
        {!(data.currentVariant === 'ScreenTablet') &&
          !(data.currentVariant === 'ScreenMobile') && (
            <EmpoweringSuccessSto data={data}>
              <EmpoweringSuccessStoSpan1
                data={data}
              >{`Empowering `}</EmpoweringSuccessStoSpan1>
              <EmpoweringSuccessStoSpan2
                data={data}
              >{`Success Stories`}</EmpoweringSuccessStoSpan2>
            </EmpoweringSuccessSto>
          )}
        {!(data.currentVariant === 'ScreenTablet') &&
          !(data.currentVariant === 'ScreenMobile') && (
            <RevolutionizingTheWo data={data}>
              {`Revolutionizing the workplace with Microsoft Surface products, we deliver tailored solutions and training to elevate efficiency, inspire collaboration, and drive success for businesses of all sizes.`}
            </RevolutionizingTheWo>
          )}
        {!(data.currentVariant === 'ScreenTablet') &&
          !(data.currentVariant === 'ScreenMobile') && (
            <Customers data={data}>
              <CustomerCard1 />
              <CustomerCard2 />
            </Customers>
          )}
        {!(data.currentVariant === 'ScreenTablet') &&
          !(data.currentVariant === 'ScreenMobile') && (
            <CaseBackground data={data}>
              <CaseContent>
                <CaseText>
                  <ReykjavikUniversity>
                    {`Reykjavik University`}
                  </ReykjavikUniversity>
                  <WithMicrosoftSurface>
                    {`With Microsoft Surface Studio devices in all classrooms at Reykjavík University the organization has taken a digital leap into the future. Teachers are integrating new tools and techniques in their teaching that resonate with the 21st century skills.`}
                  </WithMicrosoftSurface>
                </CaseText>
                <DownloadPdf>
                  <Base>
                    <MaskedIcon>
                      <SvgIcon component={ChevronLeftIcon}></SvgIcon>
                      <Vector
                        src={`assets/images/CustomerCases_Vector_1.png`}
                        loading="lazy"
                        alt={'Vector'}
                      />
                    </MaskedIcon>
                    <Button1>{`DOWNLOAD CUSTOMER CASE`}</Button1>
                    {false && (
                      <MaskedIcon1>
                        <SvgIcon
                          component={ChevronRightIcon}
                          htmlColor={`primary/contrast`}
                        ></SvgIcon>
                      </MaskedIcon1>
                    )}
                  </Base>
                </DownloadPdf>
              </CaseContent>
            </CaseBackground>
          )}
        {data.currentVariant === 'ScreenTablet' && (
          <EmpoweringSuccessSto1 data={data}>
            <EmpoweringSuccessSto1Span1
              data={data}
            >{`Empowering `}</EmpoweringSuccessSto1Span1>
            <EmpoweringSuccessSto1Span2
              data={data}
            >{`Success Stories`}</EmpoweringSuccessSto1Span2>
          </EmpoweringSuccessSto1>
        )}
        {data.currentVariant === 'ScreenTablet' && (
          <RevolutionizingTheWo1 data={data}>
            {`Revolutionizing the workplace with Microsoft Surface products, we deliver tailored solutions and training to elevate efficiency, inspire collaboration, and drive success for businesses of all sizes.`}
          </RevolutionizingTheWo1>
        )}
        {data.currentVariant === 'ScreenTablet' && (
          <Customers1 data={data}>
            <CustomerCard3 />
            <CustomerCard4 />
            <CustomerCard5 />
          </Customers1>
        )}
        {data.currentVariant === 'ScreenTablet' && (
          <CaseBackground1 data={data}>
            <CaseContent1>
              <CaseText1>
                <ReykjavikUniversity1>
                  {`Reykjavik University`}
                </ReykjavikUniversity1>
                <WithMicrosoftSurface1>
                  {`With Microsoft Surface Studio devices in all classrooms at Reykjavík University the organization has taken a digital leap into the future. Teachers are integrating new tools and techniques in their teaching that resonate with the 21st century skills.`}
                </WithMicrosoftSurface1>
              </CaseText1>
              <DownloadPdf1>
                <Base1>
                  <MaskedIcon2>
                    <SvgIcon component={ChevronLeftIcon}></SvgIcon>
                    <Vector1
                      src={`assets/images/CustomerCases_Vector_4.png`}
                      loading="lazy"
                      alt={'Vector'}
                    />
                  </MaskedIcon2>
                  <Button2>{`DOWNLOAD CUSTOMER CASE`}</Button2>
                  {false && (
                    <MaskedIcon3>
                      <SvgIcon
                        component={ChevronRightIcon}
                        htmlColor={`primary/contrast`}
                      ></SvgIcon>
                    </MaskedIcon3>
                  )}
                </Base1>
              </DownloadPdf1>
            </CaseContent1>
          </CaseBackground1>
        )}
        {data.currentVariant === 'ScreenMobile' && (
          <EmpoweringSuccessSto2 data={data}>
            <EmpoweringSuccessSto2Span1 data={data}>{`Empowering
`}</EmpoweringSuccessSto2Span1>
            <EmpoweringSuccessSto2Span2
              data={data}
            >{`Success Stories`}</EmpoweringSuccessSto2Span2>
          </EmpoweringSuccessSto2>
        )}
        {data.currentVariant === 'ScreenMobile' && (
          <RevolutionizingTheWo2 data={data}>
            {`Revolutionizing the workplace with Microsoft Surface products, we deliver tailored solutions and training to elevate efficiency, inspire collaboration, and drive success for businesses of all sizes.`}
          </RevolutionizingTheWo2>
        )}
        {data.currentVariant === 'ScreenMobile' && (
          <Customers2 data={data}>
            <CustomerCard6 />
            <CustomerCard7 />
            <CustomerCard8 />
          </Customers2>
        )}
        {data.currentVariant === 'ScreenMobile' && (
          <Cases data={data}>
            <CaseBackground2></CaseBackground2>
            <CaseContent2>
              <CaseText2>
                <ReykjavikUniversity2>
                  {`Reykjavik University`}
                </ReykjavikUniversity2>
                <WithMicrosoftSurface2>
                  {`With Microsoft Surface Studio devices in all classrooms at Reykjavík University the organization has taken a digital leap into the future. Teachers are integrating new tools and techniques in their teaching that resonate with the 21st century skills.`}
                </WithMicrosoftSurface2>
              </CaseText2>
              <DownloadPdf2>
                <Base2>
                  <MaskedIcon4>
                    <SvgIcon component={ChevronLeftIcon}></SvgIcon>
                    <Vector2
                      src={`assets/images/CustomerCases_Vector_7.png`}
                      loading="lazy"
                      alt={'Vector'}
                    />
                  </MaskedIcon4>
                  <Button3>{`DOWNLOAD CUSTOMER CASE`}</Button3>
                  {false && (
                    <MaskedIcon5>
                      <SvgIcon
                        component={ChevronRightIcon}
                        htmlColor={`primary/contrast`}
                      ></SvgIcon>
                    </MaskedIcon5>
                  )}
                </Base2>
              </DownloadPdf2>
            </CaseContent2>
          </Cases>
        )}
      </Rows>
    </ScreenDesktop>
  );
}

export default CustomerCases;
