/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { Button } from '@mui/material';
import { styled } from '@mui/material/styles';
import { ProductBox1Props } from 'types';

const ProductBox11: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(241, 241, 241, 0.95)`,
  borderRadius: `10px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `16px 0px 0px 0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
}));

const ProductImage: any = styled('img')({
  height: `209px`,
  width: `311px`,
  objectFit: `cover`,
  margin: `0px`,
});

const ProductTitle: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 1)`,
  fontStyle: `normal`,
  fontFamily: `Open Sans`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `-0.8399999737739563px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  height: `68px`,
  width: `311px`,
  margin: `24px 0px 0px 0px`,
});

const Description: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: theme.palette['MOWO']['black-75'],
  fontStyle: `normal`,
  fontFamily: `Open Sans`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `-0.3199999928474426px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  height: `69px`,
  width: `273px`,
  margin: `24px 0px 0px 0px`,
}));

const ButtonOutlined: any = styled(Button)(({ theme }: any) => ({
  margin: `24px 0px 0px 0px`,
  color: theme.palette['Info']['Main'],
  fontStyle: theme.typography['Components']['Button Font - Medium'].fontStyle,
  fontFamily: theme.typography['Components']['Button Font - Medium'].fontFamily,
  fontWeight: theme.typography['Components']['Button Font - Medium'].fontWeight,
  fontSize: theme.typography['Components']['Button Font - Medium'].fontSize,
  letterSpacing:
    theme.typography['Components']['Button Font - Medium'].letterSpacing,
  lineHeight: theme.typography['Components']['Button Font - Medium'].lineHeight,
  textDecoration:
    theme.typography['Components']['Button Font - Medium'].textDecoration,
  textTransform:
    theme.typography['Components']['Button Font - Medium'].textTransform,
}));

const Rectangle178: any = styled('div')(({ theme }: any) => ({
  backgroundColor: theme.palette['Secondary']['Main'],
  alignSelf: `stretch`,
  height: `15px`,
  margin: `24px 0px 0px 0px`,
}));

function ProductBox1(props: ProductBox1Props): JSX.Element {
  return (
    <ProductBox11 className={props.className}>
      <ProductImage
        src={`assets/images/ProductBox1_Product_Image.png`}
        loading="lazy"
        alt={'Product Image'}
      />
      <ProductTitle>{`Surface Go 3`}</ProductTitle>
      <Description>
        {`Surface Pro 5. Elegant design meets workplace mobility. Redefining productivity on the move.`}
      </Description>
      <ButtonOutlined
        variant="outlined"
        size={'medium'}
        color={'info'}
        disabled={false}
      >
        {'Device Details'}
      </ButtonOutlined>
      <Rectangle178></Rectangle178>
    </ProductBox11>
  );
}

export default ProductBox1;
