/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import ProductImageImage from 'src/assets/images/ProductCard_Product_Image.png';
import { styled } from '@mui/material/styles';

const Property1Desktop = styled('div')({
  borderRadius: `10px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `500px`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const ProductCard1 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(241, 241, 241, 0.95)`,
  border: `1px solid rgba(0, 164, 239, 1)`,
  boxSizing: `border-box`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `15px 0px 45px 0px`,
  alignSelf: `stretch`,
  flex: `1`,
  margin: `0px`,
}));

const ProductImage = styled('img')({
  height: `200px`,
  width: `300px`,
  objectFit: `cover`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Title = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `700`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `133.39999914169312%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`,
}));

const DescriptionMax = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 0.75)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `150%`,
  textTransform: `none`,
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Button1 = styled('div')({
  border: `1px solid rgba(51, 51, 51, 0.75)`,
  boxSizing: `border-box`,
  borderRadius: `6px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  margin: `0px`,
});

const Details = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 0.75)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0.15000000596046448px`,
  textDecoration: `none`,
  lineHeight: `133.39999914169312%`,
  textTransform: `none`,
  width: `129px`,
  height: `34px`,
  margin: `0px`,
}));

function ProductCard(props) {
  return (
    <Property1Desktop className={props.className}>
      <ProductCard1>
        <ProductImage
          src={ProductImageImage}
          loading="lazy"
          alt={'Product Image'}
        />
        <Title>{`Title`}</Title>
        <DescriptionMax>
          {`Description
.
max.`}
        </DescriptionMax>
        <Button1>
          <Details>{`DETAILS`}</Details>
        </Button1>
      </ProductCard1>
    </Property1Desktop>
  );
}

export default ProductCard;
