/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import ProductBox1 from 'components/ProductBox1/ProductBox1';
import { Frame139Props } from 'types';
import useFrame139 from 'components/Frame139/useFrame139';

const Frame1391: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `499px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const ProductBox11: any = styled(ProductBox1)(({ theme }: any) => ({
  width: `311px`,
  height: `499px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

function Frame139(props: Frame139Props): JSX.Element {
  const { data } = useFrame139();

  return (
    <Frame1391 className={props.className}>
      {data.products &&
        data.products.map((product: any, index: number) => {
          return <ProductBox11 key={index} />;
        })}
    </Frame1391>
  );
}

export default Frame139;
