/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React, { useState } from 'react';

const useLink1 = () => {
  const [isFocus, setIsFocus] = useState(false);
  const [isHover, setIsHover] = useState(false);

  const data: any = { isFocus, isHover };

  const fns: any = {
    handleFocus: () => {
      setIsFocus(true);
    },
    handleBlur: () => {
      setIsFocus(false);
    },
    handleMouseEnter: () => {
      setIsHover(true);
    },
    handleMouseLeave: () => {
      setIsHover(false);
    },
  };

  return { data, fns };
};

export default useLink1;
