/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { ProductCardTempProps } from 'types';
import useProductCardTemp from 'components/ProductCardTemp/useProductCardTemp';

const ProductCardTemp1: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(241, 241, 241, 0.95)`,
  borderRadius: `10px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: '100%',
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `16px 0px 0px 0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
}));

const Imagecontainer: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `208px`,
  margin: `0px`,
});

const ProductImage: any = styled('img')({
  height: `208px`,
  width: `258px`,
  objectFit: `cover`,
  flex: `1`,
  margin: `0px`,
});

function ProductCardTemp(props: ProductCardTempProps): JSX.Element {
  const { data, fns } = useProductCardTemp();

  return (
    <ProductCardTemp1 className={props.className}>
      {data.products &&
        data.products.map((product: any, index: number) => {
          return (
            <Imagecontainer key={index}>
              <ProductImage
                src={props.products.image.src}
                loading="lazy"
                alt={'product image'}
              />
            </Imagecontainer>
          );
        })}
    </ProductCardTemp1>
  );
}

export default ProductCardTemp;
