/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Header from 'components/Header/Header';
import ModernWorkplace from 'components/ModernWorkplace/ModernWorkplace';
import ProductSectionSurfaceHubDevice from 'components/ProductSectionSurfaceHubDevice/ProductSectionSurfaceHubDevice';
import CustomerCases from 'components/CustomerCases/CustomerCases';
import Footer from 'components/Footer/Footer';
import Navbar from 'components/Navbar/Navbar';
import { MowoFunProps } from 'types';
import useMowoFun from 'components/MowoFun/useMowoFun';

const ScreenDesktop: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: 'auto',
});

const Header1: any = styled(Header)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const ModernWorkplace1: any = styled(ModernWorkplace)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const ProductSectionSurfac: any = styled(ProductSectionSurfaceHubDevice)(
  ({ theme }: any) => ({
    alignSelf: `stretch`,
    margin: `0px`,
  })
);

const CustomerCases1: any = styled(CustomerCases)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Footer1: any = styled(Footer)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Navbar1: any = styled(Navbar)(({ theme }: any) => ({
  width: `1440px`,
  margin: `0px`,
}));

const Header2: any = styled(Header)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const ModernWorkplace2: any = styled(ModernWorkplace)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const ProductSectionSurfac1: any = styled(ProductSectionSurfaceHubDevice)(
  ({ theme }: any) => ({
    alignSelf: `stretch`,
    margin: `0px`,
  })
);

const CustomerCases2: any = styled(CustomerCases)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Footer2: any = styled(Footer)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Header3: any = styled(Header)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const ModernWorkplace3: any = styled(ModernWorkplace)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const ProductSectionSurfac2: any = styled(ProductSectionSurfaceHubDevice)(
  ({ theme }: any) => ({
    alignSelf: `stretch`,
    margin: `0px`,
  })
);

const CustomerCases3: any = styled(CustomerCases)(({ theme }: any) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Footer3: any = styled(Footer)(({ theme }: any) => ({
  alignSelf: `stretch`,
  height: `504px`,
  margin: `0px`,
}));

function MowoFun(props: MowoFunProps): JSX.Element {
  const { data } = useMowoFun();

  return (
    <ScreenDesktop className={props.className}>
      {!(data.currentVariant === 'Tablet') &&
        !(data.currentVariant === 'ScreenMobile') && <Header1 />}
      {!(data.currentVariant === 'Tablet') &&
        !(data.currentVariant === 'ScreenMobile') && <ModernWorkplace1 />}
      {!(data.currentVariant === 'Tablet') &&
        !(data.currentVariant === 'ScreenMobile') && <ProductSectionSurfac />}
      {!(data.currentVariant === 'Tablet') &&
        !(data.currentVariant === 'ScreenMobile') && <CustomerCases1 />}
      {!(data.currentVariant === 'Tablet') &&
        !(data.currentVariant === 'ScreenMobile') && <Footer1 />}
      {!(data.currentVariant === 'Tablet') &&
        !(data.currentVariant === 'ScreenMobile') && <Navbar1 />}
      {data.currentVariant === 'Tablet' && <Header2 />}
      {data.currentVariant === 'Tablet' && <ModernWorkplace2 />}
      {data.currentVariant === 'Tablet' && <ProductSectionSurfac1 />}
      {data.currentVariant === 'Tablet' && <CustomerCases2 />}
      {data.currentVariant === 'Tablet' && <Footer2 />}
      {data.currentVariant === 'ScreenMobile' && <Header3 />}
      {data.currentVariant === 'ScreenMobile' && <ModernWorkplace3 />}
      {data.currentVariant === 'ScreenMobile' && <ProductSectionSurfac2 />}
      {data.currentVariant === 'ScreenMobile' && <CustomerCases3 />}
      {data.currentVariant === 'ScreenMobile' && <Footer3 />}
    </ScreenDesktop>
  );
}

export default MowoFun;
