/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { ProductBox3Props } from 'types';

const ProductBox31: any = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `499px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Bg: any = styled('div')({
  backgroundColor: `rgba(241, 241, 241, 0.95)`,
  border: `1px solid rgba(0, 164, 239, 1)`,
  boxSizing: `border-box`,
  borderRadius: `10px`,
  width: `311px`,
  height: `499px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const ProductImage: any = styled('img')({
  height: `208px`,
  width: `309px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `30px`,
});

const ProductTitle: any = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(51, 51, 51, 1)`,
  fontStyle: `normal`,
  fontFamily: `Open Sans`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `-0.8399999737739563px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  width: `311px`,
  height: `68px`,
  position: `absolute`,
  left: `0px`,
  top: `235px`,
});

const Description: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: theme.palette['MOWO']['black-75'],
  fontStyle: `normal`,
  fontFamily: `Open Sans`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `-0.3199999928474426px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  width: `273px`,
  height: `69px`,
  position: `absolute`,
  left: `19px`,
  top: `313px`,
}));

const Button1: any = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `200px`,
  height: `35px`,
  left: `56px`,
  top: `410px`,
});

const Rectangle6: any = styled('div')({
  border: `1px solid rgba(51, 51, 51, 1)`,
  boxSizing: `border-box`,
  borderRadius: `10px`,
  width: `200px`,
  height: `35px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const DeviceDetails: any = styled('div')(({ theme }: any) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: theme.palette['MOWO']['black-75'],
  fontStyle: `normal`,
  fontFamily: `Open Sans`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.3199999928474426px`,
  textDecoration: `none`,
  lineHeight: `20px`,
  textTransform: `none`,
  width: `199px`,
  height: `35px`,
  position: `absolute`,
  left: `1px`,
  top: `0px`,
}));

function ProductBox3(props: ProductBox3Props): JSX.Element {
  return (
    <ProductBox31 className={props.className}>
      <Bg></Bg>
      <ProductImage
        src={`assets/images/ProductBox3_Product_Image.png`}
        loading="lazy"
        alt={'Product Image'}
      />
      <ProductTitle>{`Surface Pro 9`}</ProductTitle>
      <Description>
        {`Surface Pro 5. Elegant design meets workplace mobility. Redefining productivity on the move.`}
      </Description>
      <Button1>
        <Rectangle6></Rectangle6>
        <DeviceDetails>{`DEVICE DETAILS`}</DeviceDetails>
      </Button1>
    </ProductBox31>
  );
}

export default ProductBox3;
