/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React, { useState } from 'react';

const useProductCardList = () => {
  const items = [
    {
      title: 'Product 1',
      description: 'This is product 1',
      image: '',
    },
    {
      title: 'Product 2',
      description: 'This is product 2',
      image: '',
    },
    {
      title: 'Product 3',
      description: 'This is product 3',
      image: '',
    },
  ]
  let [index, setIndex] = useState();
  let data: any = { items, index};

  const fns: any = {};

  return { data, fns };
};

export default useProductCardList;
