/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React, { useState } from 'react';
import useProductCardNew from 'components/ProductCardNew/useProductCardNew';

const useProductCardList = () => {

  const { data } = useProductCardNew();

  const fns: any = {};

  return { data, fns };
};

export default useProductCardList;
