/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { ClientLogoCardProps } from 'types';

const ClientLogoCard1: any = styled('div')(({ theme }: any) => ({
  backgroundColor: `rgba(241, 241, 241, 0.95)`,
  borderRadius: `10px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `16px`,
  boxSizing: `border-box`,
  height: `92px`,
  width: `212px`,
}));

const HaskolinnLogo1: any = styled('img')({
  height: `60px`,
  width: `180px`,
  objectFit: `cover`,
  margin: `0px`,
});

function ClientLogoCard(props: ClientLogoCardProps): JSX.Element {
  return (
    <ClientLogoCard1 className={props.className}>
      <HaskolinnLogo1
        src={props.logo.src}
        loading="lazy"
        alt={props.logo.alt}
      />
    </ClientLogoCard1>
  );
}

export default ClientLogoCard;
