/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import useProductCardList from 'components/ProductCardList/useProductCardList';

/* These are the possible values for the current variant. Use this to change the currentVariant dynamically.
Please don't modify */
const variantOptions = {
  StateDefault: 'StateDefault',
  StateHover: 'StateHover',
};

const useProductCardNew = () => {
  const [currentVariant, setCurrentVariant] = React.useState<string>(
    variantOptions['StateDefault']
  );
  const [previousVariant, setPreviousVariant] = React.useState<string>('');

  const { data } = useProductCardList();

  const getImageSrc = (): any => {};

  const fns: any = { getImageSrc, setCurrentVariant, setPreviousVariant };

  return { data: { ...data, currentVariant, previousVariant }, fns };
};

export default useProductCardNew;
