/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
const useMenulinklist = () => {
const menuLinks = [
  {
    id: 1,
    title: "Modern Workplace",
    url: "/",
  },
  {
    id: 2,
    title: "Solutions",
    url: "/",
  },
  {
    id: 3,
    title: "Devices",
    url: "/",
  },
  {
    id: 4,
    title: "Cases",
    url: "/",
  },
  {
    id: 5,
    title: "Contact",
    url: "/",
  },
];

  let data: any = { menuLinks };

  const fns: any = {};

  return { data, fns };
};

export default useMenulinklist;
