/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React, { useState } from 'react';

const useProductBox = () => {
  const [products, setProducts] = useState([
    {
      id: 1,
      name: 'Product 1',
      title: 'Product 1',
      isProduct: false,
    },
    {
      id: 2,
      name: 'Product 2',
      title: 'Product 2',
      isProduct: false,
    },
  ]);

  const setState = (newState: any) => {
    setProducts((prevProducts) => ({ ...prevProducts, ...newState }));
  };

  const handleProductClick = (productId: number, setState: any) => {
    setState({
      products: products.map((product) =>
        product.id === productId ? { ...product, isProduct: !product.isProduct } : product
      ),
    });
  };

  const data: any = { products };
  const fns: any = { handleProductClick };

  return { data, fns, setState };
};

export default useProductBox;