/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *   Do not change the name of the hook
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React, { useState } from 'react';

const useProductBox = () => {
  const [data, setData] = useState({
    isProduct: false,
    isProduct2: false,
    isProduct3: false,
    isProduct4: false,
    isProduct5: false,
    isProduct6: false,
  });

  const handleButtonClick = (): any => {
    setData ({ ...data, isProduct: !data.isProduct })
  };

  const fns: any = {handleButtonClick};

  return { data, fns };
};

export default useProductBox;
